### ISSUE TITLE
EPaperDisplay object cannot assign attribute 'rotation'

### ISSUE THREAD

**Issue by djotaku** [adafruit/Adafruit_CircuitPython_MagTag#47]
Using the example code from this repo. I *had* been working on the weather tutorial on the Adafruit site, but wanted to eliminate potential sources of error.

Following in the lib folder: (from the 20201225 circuit python libraries)

Folders:
- adafruit_bitmap_font
- adafrui_display_text
- adafruit_imageload
- adafruit_io
- adafruit_magtag
- adafruit_portalbase

Files:

- adafruit_fakerequests
- adafruit_iniiqr
- adafruit_requests
- neopixel
- simpleio

Whenever the code reloads, I get: 
code.py output:
Traceback (most recent call last):
  File "code.py", line 5, in <module>
  File "adafruit_magtag/magtag.py", line 84, in __init__
  File "adafruit_magtag/graphics.py", line 57, in __init__
AttributeError: 'EPaperDisplay' object cannot assign attribute 'rotation'

**Comment by djotaku** [comment]
Nevermind, loading the latest UF2 fixes the issue.
