### ISSUE TITLE
Speaker can only play so many tones

### ISSUE THREAD

**Issue by KTibow** [adafruit/Adafruit_CircuitPython_MagTag#57]
## Problem
I found when I use `play_tone`, I can only play so many separate tones. So I can play 500 as many times as I want, at any speed. But if then I play 490, then 480, and so on, eventually it stops working.
## Explanation
The library uses `simpleio.tone`. It gives the error
```python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "simpleio.py", line 65, in tone
NameError: name 'AudioOut' is not defined
```
eventually. This is caused by a `ValueError`, which is catched, and causes it to proceed to the line
```
        with AudioOut(pin) as dac:
```
This fails, because the only working solution is `pwmio`. Now, here's the exact `ValueError`:
```python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in beep
ValueError: No more timers available
```
I believe this is caused by not cleaning up after the PWM instance once used.
## Suggested solution
In the MagTag library, import pwmio instead of simpleio. Allocate a variable frequency PWM. Replace the function
```
    def play_tone(self, frequency, duration):
        """Automatically Enable/Disable the speaker and play
        a tone at the specified frequency for the specified duration
        It will attempt to play the sound up to 3 times in the case of
        an error.
        """
        if frequency <= 0:
            raise ValueError("The frequency has to be greater than 0.")
        self._speaker_enable.value = True
        attempt = 0
        # Try up to 3 times to play the sound
        while attempt < 3:
            try:
                simpleio.tone(board.SPEAKER, frequency, duration)
                break
            except NameError:
                pass
            attempt += 1
        self._speaker_enable.value = False
```
with
```
    def play_tone(self, frequency, duration):
        """Automatically Enable/Disable the speaker and play
        a tone at the specified frequency for the specified duration
        It will attempt to play the sound up to 3 times in the case of
        an error.
        """
        if frequency <= 0:
            raise ValueError("The frequency has to be greater than 0.")
        self._speaker_enable.value = True
        self._speaker.duty_cycle = 0x8000
        self._speaker.frequency = frequency
        time.sleep(duration)
        self._speaker.duty_cycle = 0
        self._speaker_enable.value = False
```
## Alternative solutions
Fix the bug where it doesn't free up the timer in `simpleio`.

Feel free to correct me or to suggest edits in any of this issue.

**Comment by tannewt** [comment]
Sounds like you made great progress tracking this down! Thanks!

Is there a CircuitPython bug for leaking timers in `pwmio`? That'd be good to get fixed.

**Comment by KTibow** [comment]
I believe. I can reproduce it with this code:
```
import board, digitalio, pwmio, time

speaker_enable = digitalio.DigitalInOut(board.SPEAKER_ENABLE)
speaker_enable.switch_to_output()
speaker_enable.value = True

for i in range(300, 700, 25):
    speaker = pwmio.PWMOut(board.SPEAKER, duty_cycle=0x8000, frequency=i)
    time.sleep(0.3)
    speaker.deinit()
```
At least in the esp32s2 implementation.

**Comment by tannewt** [comment]
Ok, I'm going to move this to the CircuitPython repo. It sounds like a bug there.
